cloudAdministratorUsername: "admin"
cloudIntegrationPlatformNamespace: "integration"
#Gowtham: Default is true.
productionDeployment: MY_productionDeployment
clusterDomainSuffix: cluster.local

global:
  registry: "cp.icr.io/cp/icp4i/apic"
  #Gowtham: Set the value for this. It was empty
  registrySecret: MY_registrySecret
  createCrds: true
  #Gowtham: By default it is Empty. In IBM Cloud the right choice is ibmc-block-gold
  storageClass: MY_storageClass
  #Gowtham: Default is 'standard'
  mode: MY_mode
  routingType: "route"
  certSecret: ""
  extraValuesConfig: ""
  nodeTuning:
    enabled: true

# apiconnect-operator
operator:
  arch: amd64
  registry: ""
  image: "apiconnect-operator"
  tag: 2020-03-04-13-22-09-8261833ecf78a1aa3f3b85b7bd92c7dca6762000
  pullPolicy: IfNotPresent
  #Gowtham: set this value. this was empty
  helmTlsSecret: MY_helmTlsSecret
  serviceAccount:
    create: true
    name:
  tiller:
    useNodePort: false
    nodePort: 31514

# management subsystem
management:
  enabled: true
  name: management
  certSecret: ""
  storageClass: ""
  #Gowtham: Set the below 4 properties
  platformApiEndpoint: MY_platformApiEndpoint
  consumerApiEndpoint: MY_consumerApiEndpoint
  cloudAdminUiEndpoint: MY_cloudAdminUiEndpoint
  apiManagerUiEndpoint: MY_apiManagerUiEndpoint
cassandra:
  #Gowtham: default value is 3
  cassandraClusterSize: MY_cassandraClusterSize
  cassandraMaxMemoryGb: 9
  cassandraVolumeSizeGb: 50
cassandraBackup:
  cassandraBackupAuthUser: ""
  cassandraBackupAuthPass: ""
  cassandraBackupHost: ""
  cassandraBackupPath: /backups
  cassandraBackupPort: 22
  cassandraBackupProtocol: sftp
  cassandraBackupSchedule: 0 0 * * *
cassandraPostmortems:
  cassandraPostmortemsAuthUser: ""
  cassandraPostmortemsAuthPass: ""
  cassandraPostmortemsHost: ""
  cassandraPostmortemsPath: /cassandra-postmortems
  cassandraPostmortemsPort: 22
  cassandraPostmortemsSchedule: 0 0 * * *

# portal subsystem
portal:
  enabled: true
  name: portal
  certSecret: ""
  storageClass: ""
  #Gowtham: Set the below 2 properties
  portalDirectorEndpoint: MY_portalDirectorEndpoint
  portalWebEndpoint: MY_portalWebEndpoint
  adminStorageSizeGb: 1
  backupStorageSizeGb: 5
  dbLogsStorageSizeGb: 2
  dbStorageSizeGb: 12
  wwwStorageSizeGb: 5

portalBackup:
  siteBackupAuthUser: ""
  siteBackupAuthPass: ""
  siteBackupHost: ""
  siteBackupPath: /backups
  siteBackupPort: 22
  siteBackupProtocol: sftp
  siteBackupSchedule: 0 2 * * *

# analytics subsystem
analytics:
  enabled: true
  name: analytics
  certSecret: ""
  storageClass: ""
  esStorageClass: ""
  enableMessageQueue: false
  mqStorageClass: ""
  #Gowtham: Set the below 2 properties
  analyticsIngestionEndpoint: MY_analyticsIngestionEndpoint
  analyticsClientEndpoint: MY_analyticsClientEndpoint
  coordinatingMaxMemoryGb: 12
  dataMaxMemoryGb: 12
  dataStorageSizeGb: 100
  masterMaxMemoryGb: 12
  masterStorageSizeGb: 5

# gateway subsystem
gateway:
  enabled: true
  name: gateway
  certSecret: ""
  storageClass: ""
  #Gowtham: Set the below 2 properties
  apiGatewayEndpoint: MY_apiGatewayEndpoint
  gatewayServiceEndpoint: MY_gatewayServiceEndpoint
  #Gowtham: Default value is 3. 
  replicaCount: MY_gateway_replicaCount
  maxCpu: 4
  maxMemoryGb: 6
  v5CompatibilityMode: true
  enableTms: false
  tmsPeeringStorageSizeGb: 10
  #Gowtham: Default is on
  highPerformancePeering: MY_gateway_highPerformancePeering
  image: datapower-api-gateway
  imageTag: 2018.4.1.10u-318372u-release-ubi-prod
  monitoringImage: "k8s-datapower-monitor"
  monitoringImageTag: 2018.4.1.10u-icp4i
  odTracing:
    #Gowtham: Default is false
    enabled: MY_odTracing_enabled

    odManagerNamespace: MY_odTracing_odManagerNamespace
    odAgentImage: "icp4i-od-agent"
    odAgentImageTag: "1.0.2"
    odCollectorImage: "icp4i-od-collector"
    odCollectorImageTag: "1.0.2"
  imagePullPolicy: IfNotPresent

# additional gateway subsystem
gateway2:
  enabled: false
  name: gateway2
  certSecret: ""
  storageClass: ""
  apiGatewayEndpoint: ""
  gatewayServiceEndpoint: ""
  replicaCount: 3
  maxCpu: 4
  maxMemoryGb: 6
  v5CompatibilityMode: true
  enableTms: false
  tmsPeeringStorageSizeGb: 10
  highPerformancePeering: on
  image: datapower-api-gateway
  imageTag: 2018.4.1.10u-318372u-release-ubi-prod
  monitoringImage: "k8s-datapower-monitor"
  monitoringImageTag: 2018.4.1.10u-icp4i
  odTracing:
    enabled: false
    odManagerNamespace: ""
    odAgentImage: "icp4i-od-agent"
    odAgentImageTag: "1.0.2"
    odCollectorImage: "icp4i-od-collector"
    odCollectorImageTag: "1.0.2"
  imagePullPolicy: IfNotPresent